# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to=b'mascotas'),
        ),
    ]
